image: maven:3-eclipse-temurin-17-alpine

stages:
    - build

cache:
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"


build:
  stage: build
  artifacts:
    paths:
      - target/*.jar
  script:
    - mvn clean package
